version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: picateclasUnahur
      POSTGRES_DB: cartelera
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'

  nats:
    image: nats
    container_name: nats
    ports:
      - '4222:4222'
    restart: always
